import asyncio
from types import SimpleNamespace
from unittest import mock

from areal.api.io_struct import GenerationHyperparameters, ModelRequest
from areal.infra.remote_inf_engine import RemoteInfEngine


def _build_engine(versions_seen):
    """Engine whose weight version advances while a request is in flight."""
    engine = RemoteInfEngine.__new__(RemoteInfEngine)
    engine._version = 10
    engine.config = SimpleNamespace(
        use_lora=False,
        request_retries=1,
        request_timeout=1,
        return_routed_experts=False,
        enable_rollout_tracing=False,
        routing_strategy="round_robin",
    )
    engine.addresses = ["127.0.0.1:8000"]
    engine.rid_to_address = {}
    engine.rid_queue = []
    engine.server_idx = 0
    engine.workflow_executor = SimpleNamespace(is_paused=lambda: False)

    def _get_version():
        return engine._version

    engine.get_version = _get_version

    def _build_generation_request(req, with_lora, version):
        versions_seen.append(("request", version))
        return SimpleNamespace(endpoint="/generate", payload={}, method="POST")

    def _parse_generation_response(_response):
        # The weight update lands while the request is in flight.
        engine._version = 11
        return SimpleNamespace(
            output_tokens=[1, 2, 3],
            output_logprobs=[0.0, 0.0, 0.0],
            stop_reason="stop",
            routed_experts=None,
        )

    engine.backend = SimpleNamespace(
        build_generation_request=_build_generation_request,
        parse_generation_response=_parse_generation_response,
    )
    return engine


def test_output_versions_use_the_version_that_served_the_request():
    versions_seen = []
    engine = _build_engine(versions_seen)
    gconfig = GenerationHyperparameters(max_new_tokens=3)
    req = ModelRequest(rid="r0", input_ids=[1, 2], gconfig=gconfig)

    with (
        mock.patch(
            "areal.infra.remote_inf_engine.arequest_with_retry",
            new=mock.AsyncMock(return_value={}),
        ),
        mock.patch("areal.infra.remote_inf_engine.workflow_context") as ctx,
    ):
        ctx.get_aiohttp_session = mock.AsyncMock(return_value=None)
        response = asyncio.run(engine.agenerate(req))

    assert versions_seen == [("request", 10)]
    assert engine.get_version() == 11
    assert response.output_versions == [10, 10, 10], (
        "tokens generated by version 10 must not be labelled with version 11"
    )
