#!/usr/bin/env python3
"""Run one real Archon engine train step for DTA comparison tests.

The pytest side launches this script twice with torchrun: once for regular
Archon DP/FSDP, once for DTA Zero1. Rank 0 writes full CPU gradient and
parameter-update tensors for pytest to compare element-wise.
"""

from __future__ import annotations

import argparse
import functools
import os
from dataclasses import asdict
from pathlib import Path
from typing import Any

import torch
import torch.distributed as dist
from torch.distributed.tensor import DTensor

from tests.experimental.dta.engine_step_case import EngineStepCase

from areal.api import FinetuneSpec, ParallelStrategy
from areal.api.cli_args import MicroBatchSpec, OptimizerConfig, TrainEngineConfig
from areal.experimental.engine.archon_engine import ArchonLMEngine
from areal.infra.platforms import current_platform
from areal.utils.data import concat_batch
from areal.utils.functional import ppo_actor_loss_fn


def _build_trajectory(seq: torch.Tensor) -> dict[str, torch.Tensor]:
    input_ids = seq.unsqueeze(0).contiguous()
    attention_mask = torch.ones_like(input_ids, dtype=torch.bool)
    loss_mask = torch.ones_like(input_ids, dtype=torch.float32)
    loss_mask[:, 0] = 0.0
    loss_mask[:, -1] = 0.0
    return {
        "input_ids": input_ids,
        "attention_mask": attention_mask,
        "loss_mask": loss_mask,
    }


def build_local_batch(sequences: list[torch.Tensor], dp_rank: int, dp_world_size: int):
    local_sequences = [
        seq for idx, seq in enumerate(sequences) if idx % dp_world_size == dp_rank
    ]
    if not local_sequences:
        raise RuntimeError(
            f"No local sequences for dp_rank={dp_rank}, dp_world_size={dp_world_size}"
        )
    trajectories = [_build_trajectory(seq) for seq in local_sequences]
    batch, _ = concat_batch(trajectories)
    return batch


def _load_cot_sequences(
    case: EngineStepCase,
    *,
    vocab_size: int,
) -> list[torch.Tensor]:
    path = Path(case.sequence_data_path)
    if not path.exists():
        raise FileNotFoundError(
            "DTA engine-step COT sequence data must be generated by pytest before "
            f"torchrun starts: {path}"
        )
    sequence_metadata = case.cot_sequence_metadata()
    payload = torch.load(path, map_location="cpu", weights_only=False)
    if int(payload["vocab_size"]) != vocab_size:
        raise ValueError(
            "Saved DTA engine-step sequence vocab mismatch: "
            f"saved={payload['vocab_size']}, current={vocab_size}"
        )
    if payload["sequence_metadata"] != sequence_metadata:
        raise ValueError(
            "Saved DTA engine-step COT sequence metadata mismatch: "
            f"saved={payload['sequence_metadata']}, current={sequence_metadata}"
        )
    return payload["sequences"]


def dta_step_loss_fn(
    logprobs: torch.Tensor,
    entropy: torch.Tensor,
    input_data: dict[str, Any],
    **_: Any,
) -> torch.Tensor:
    loss_mask = input_data["loss_mask"].to(device=logprobs.device).bool()
    if logprobs.ndim != 1 or entropy.ndim != 1 or loss_mask.ndim != 1:
        raise ValueError(
            "DTA engine-step loss expects 1D packed tensors: "
            f"logprobs={tuple(logprobs.shape)}, "
            f"entropy={tuple(entropy.shape)}, "
            f"loss_mask={tuple(loss_mask.shape)}."
        )
    if logprobs.shape != entropy.shape or logprobs.shape != loss_mask.shape:
        raise ValueError(
            "DTA engine-step loss shape mismatch: "
            f"logprobs={tuple(logprobs.shape)}, "
            f"entropy={tuple(entropy.shape)}, "
            f"loss_mask={tuple(loss_mask.shape)}."
        )

    # Keep the comparison deterministic and local to this engine-step test:
    # old/prox logprobs are fixed baselines, while current logprobs and entropy
    # both contribute gradients.
    old_logprobs = logprobs.detach()
    advantages = torch.ones_like(logprobs)
    loss_fn = functools.partial(
        ppo_actor_loss_fn,
        old_logprobs=old_logprobs,
        proximal_logprobs=old_logprobs,
        advantages=advantages,
        eps_clip=0.2,
        eps_clip_higher=None,
        c_clip=None,
        rejection_sampling=None,
        importance_sampling_level="token",
        cu_seqlens=None,
    )
    ppo_loss, _ = loss_fn(logprobs=logprobs, loss_mask=loss_mask)
    entropy_bonus = torch.where(loss_mask, entropy, entropy.new_zeros(())).sum()
    entropy_bonus = entropy_bonus / loss_mask.count_nonzero().clamp(min=1)
    return ppo_loss - 0.01 * entropy_bonus


def dta_step_loss_weight_fn(input_data: dict[str, Any]) -> torch.Tensor:
    loss_mask = input_data["loss_mask"]
    return loss_mask.float().sum().to(loss_mask.device)


def _strip_wrapper_prefixes(name: str) -> str:
    return name.replace("._checkpoint_wrapped_module", "").replace("._orig_mod", "")


def _full_tensor(tensor: torch.Tensor) -> torch.Tensor:
    if isinstance(tensor, DTensor):
        tensor = tensor.full_tensor()
    return tensor.detach().float().cpu().clone()


def _canonical_name(engine: ArchonLMEngine, name: str, tensor: torch.Tensor) -> str:
    name = _strip_wrapper_prefixes(name)
    adapter = engine.state_dict_adapter
    if adapter is None:
        return name
    mapped = adapter.convert_single_to_hf(name, tensor)
    if mapped:
        return mapped[0][0]
    return name


def _snapshot_grad_tensors(engine: ArchonLMEngine) -> dict[str, torch.Tensor]:
    tensors: dict[str, torch.Tensor] = {}
    for raw_name, param in engine._get_model_name_parameters():
        if not param.requires_grad or param.grad is None:
            continue
        grad = _full_tensor(param.grad)
        name = _canonical_name(engine, raw_name, grad)
        tensors[name] = grad
    return tensors


def create_config(
    *,
    model_path: str,
    mode: str,
    dtype: str,
    dp_size: int,
    max_tokens_per_mb: int,
    dta_block_size: int,
    gradient_checkpointing: bool,
    optimizer_type: str,
    lr: float,
) -> TrainEngineConfig:
    config = TrainEngineConfig(
        path=model_path,
        experiment_name=f"dta_engine_step_{mode}",
        trial_name="torchrun",
        backend=f"archon:d{dp_size}",
        dtype=dtype,
        mb_spec=MicroBatchSpec(
            n_mbs=1,
            granularity=1,
            max_tokens_per_mb=max_tokens_per_mb,
        ),
        pad_to_maximum=False,
        gradient_checkpointing=gradient_checkpointing,
        init_from_scratch=False,
        tree_training_mode="dta" if mode == "dta" else "disabled",
        dta_block_size=dta_block_size,
        optimizer=OptimizerConfig(
            type=optimizer_type,
            lr=lr,
            weight_decay=0.0,
            lr_scheduler_type="constant",
            warmup_steps_proportion=0.0,
            gradient_clipping=1.0e9,
        ),
    )
    config.archon.attn_type = "sdpa"
    return config


def run_engine_step(case: EngineStepCase) -> dict[str, Any]:
    torch.manual_seed(1234)
    torch.cuda.manual_seed_all(1234)

    local_rank = int(os.environ["LOCAL_RANK"])
    current_platform.set_device(local_rank)
    current_platform.set_numa_affinity(local_rank)

    world_size = int(os.environ["WORLD_SIZE"])
    model_path = case.resolve_model_path()
    config = create_config(
        model_path=model_path,
        mode=case.mode,
        dtype=case.dtype,
        dp_size=world_size,
        max_tokens_per_mb=case.max_tokens_per_mb,
        dta_block_size=case.dta_block_size,
        gradient_checkpointing=case.gradient_checkpointing,
        optimizer_type=case.optimizer_type,
        lr=case.lr,
    )

    engine = ArchonLMEngine(config)
    try:
        engine.create_process_group(
            parallel_strategy=ParallelStrategy(data_parallel_size=world_size)
        )
        ft_spec = FinetuneSpec(
            total_train_epochs=1,
            dataset_size=case.dataset_size,
            train_batch_size=case.dataset_size,
        )
        engine.initialize(addr=None, ft_spec=ft_spec)
        engine.train()

        vocab_size = int(getattr(engine.model_config, "vocab_size"))
        sequences = _load_cot_sequences(
            case,
            vocab_size=vocab_size,
        )
        batch = build_local_batch(
            sequences,
            dp_rank=engine.data_parallel_rank,
            dp_world_size=engine.data_parallel_world_size,
        )

        forward_logprobs = engine.forward_batch(batch).detach().float().cpu()
        forward_loss_mask = batch["loss_mask"].detach().bool().cpu()

        stats = engine.train_batch(
            batch,
            dta_step_loss_fn,
            dta_step_loss_weight_fn,
            return_loss=True,
        )
        global_loss = torch.tensor(
            float(stats["loss"]), device=engine.device, dtype=torch.float32
        )
        dist.all_reduce(global_loss, group=engine.data_parallel_group)
        stats["global_loss"] = float(global_loss.item())
        current_platform.synchronize()
        grads = _snapshot_grad_tensors(engine)

        return {
            "case": asdict(case),
            "mode": case.mode,
            "dtype": case.dtype,
            "world_size": world_size,
            "model_path": model_path,
            "local_model_path": case.local_model_path,
            "hf_id": case.hf_id,
            "sequence_data_path": case.sequence_data_path,
            "stats": stats,
            "grads": grads,
            "forward_logprobs": forward_logprobs,
            "forward_loss_mask": forward_loss_mask,
            "num_sequences": len(sequences),
            "sequence_lengths": [int(seq.numel()) for seq in sequences],
        }
    finally:
        engine.destroy()


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--case-config", required=True)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    case = EngineStepCase.load(Path(args.case_config))
    if int(os.environ.get("RANK", "0")) == 0:
        torch.save(run_engine_step(case), case.payload_path)
    else:
        run_engine_step(case)


if __name__ == "__main__":
    main()
