experiment_name: geometry3k-sft
trial_name: trial1

seed: 1
enable_offload: false
total_train_epochs: 3
tokenizer_path: ${actor.path}

cluster:
  n_nodes: 1
  n_gpus_per_node: 16
  fileroot: /tmp/areal/experiments
  name_resolve:
    type: nfs
    nfs_record_root: /tmp/areal/name_resolve


scheduler:
  type: null

actor:
  backend: "megatron:d2p2t4"
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  path: Qwen/Qwen3.6-27B
  init_from_scratch: false
  disable_dropout: true
  gradient_checkpointing: true
  dtype: bfloat16
  mb_spec:
    max_tokens_per_mb: 4096
  optimizer:
    type: adam
    lr: 5e-7
    weight_decay: 0.01
    beta1: 0.9
    beta2: 0.999
    eps: 1e-8
    lr_scheduler_type: constant
    gradient_clipping: 1.0
    warmup_steps_proportion: 0.001
  mindspeed:
    swap_optimizer: true
    use_fused_swiglu: true
    position_embedding_type: "rope"
  megatron:
    bridge_type: megatron-bridge
  scheduling_spec:
    - task_type: worker
      port_count: 2
      gpu: 1
      mem: 32
      cmd: python3 -m areal.infra.rpc.rpc_server
      env_vars:
        TASK_QUEUE_ENABLE: "2"
        HCCL_EXEC_TIMEOUT: "14400"
        ACL_DEVICE_SYNC_TIMEOUT: "14400"
        HCCL_EVENT_TIMEOUT: "14500"
        HCCL_ASYNC_ERROR_HANDLING: "0"
        ACL_STREAM_TIMEOUT: "14500000"
        HCCL_CONNECT_TIMEOUT: "7200"
        PYTORCH_NPU_ALLOC_CONF: "expandable_segments:True"
        TORCH_COMPILE_DISABLE: "1"

train_dataset:
  batch_size: 128
  shuffle: true
  pin_memory: true
  num_workers: 4
  scheduling_spec: null
  path: hiyouga/geometry3k
  type: sft
  dataset_kwargs:
    chat_template_kwargs:
      enable_thinking: false

valid_dataset:
  split: validation
  batch_size: 128
  pin_memory: true
  num_workers: 4
  scheduling_spec: null
  path: hiyouga/geometry3k
  type: sft
  dataset_kwargs:
    chat_template_kwargs:
      enable_thinking: false

# Utilities
saver:
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  fileroot: ${cluster.fileroot}
  freq_epochs: 1
  freq_steps: null
  freq_secs: null

recover:
  mode: disabled
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  fileroot: ${cluster.fileroot}
  freq_epochs: 1
  freq_steps: null
  freq_secs: 3600

evaluator:
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  fileroot: ${cluster.fileroot}
  freq_epochs: 1
  freq_steps: null
  freq_secs: null

stats_logger:
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  fileroot: ${cluster.fileroot}
  wandb:
    mode: disabled

perf_tracer:
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  fileroot: ${cluster.fileroot}
  enabled: false
  session_tracer:
    enabled: false
