embedding:
  api_key: sk-43dd5f664179406d92fec42a9364f8a5
  base_url: http://127.0.0.1:33601/v1
  max_text_len: 8196
  model: text-embedding-3-small
  provider: openai
environment:
  alfworld_config_path: configs/envs/alfworld.yaml
  alfworld_env_type: AlfredTWEnv
experiment:
  algorithm: rl
  baseline_k: 10
  baseline_mode: null
  batch_size: 2
  bon: 0
  ckpt_eval_enabled: false
  ckpt_eval_path: null
  ckpt_resume_enabled: false
  ckpt_resume_epoch: null
  ckpt_resume_path: null
  dataset_ratio: 1.0
  enable_logging: true
  enable_value_driven: true
  experiment_name: cross_llb_hle_v2_llb_train
  few_shot_path: data/alfworld/alfworld_examples.json
  hle_categories: null
  hle_category_ratio: null
  log_level: INFO
  max_steps: 15
  mode: train
  num_sections: 3
  output_dir: /storage/openpsi/users/yl/agent-memory/MemRL/results
  random_seed: 42
  save_memories: true
  save_trajectories: true
  split_file: data/llb/os_interaction_data.json
  task: os
  test_interval: 1
  val_before_train: false
  valid_file: null
  valid_interval: 0
llm:
  api_key: sk-43dd5f664179406d92fec42a9364f8a5
  base_url: http://127.0.0.1:33601/v1
  max_tokens: 10240
  model: gpt-4o-2024-11-20
  provider: openai
  temperature: 0.0
memory:
  add_similarity_threshold: 0.99
  build_strategy: proceduralization
  checkpoint_path: null
  confidence_threshold: 0.0
  k_retrieve: 10
  load_from_checkpoint: false
  max_keywords: 8
  memory_confidence: 100.0
  mos_config_path: configs/mos_config.json
  retrieve_strategy: query
  sim_norm_mean: 0.39
  sim_norm_std: 0.14
  update_strategy: adjustment
  user_id: cross_llb_hle_v2_llb
rl_config:
  alpha: 0.3
  epsilon: 0.01
  failure_reward: 0.0
  gamma: 0.0
  novelty_threshold: 0.85
  q_init_neg: 0.5
  q_init_pos: 0.5
  q_min_threshold: -0.8
  recency_boost: 0.0
  reward_merge_gain: 0.1
  sim_threshold: 0.5
  success_reward: 1.0
  tau: 0.35
  topk: 5
  weight_q: 0.5
  weight_sim: 0.5
